### ISSUE TITLE
R CMD build fails due to broken symlink

### ISSUE THREAD

**Issue by jeroen** [mmaechler/diptest#1]
I noticed an error on: https://mmaechler.r-universe.dev/

I get the same error locally: when running `R CMD build diptest` I see:

```
cp: diptest/stuff/statlib_217_v2005.f: No such file or directory
```

The issue seems to be that `diptest/stuff/statlib_217_v2005.f` is a symlink to a file that does not exist?

**Comment by mmaechler** [comment]
Indeed.  This has been a known bug in R : The whole `./stuff/` subdirectory is in `.Rbuildignore` so `R CMD build` should not care about these...  Here's R bug report (with my own comment acknowledging it) https://bugs.r-project.org/show_bug.cgi?id=18186#c1
... patches (to R) welcome!

**Comment by mmaechler** [comment]
I've added the file to the git-managed ones, as in some sense it's meant to be part of the "background knowledge" inside `/stuff/`, also for other code readers, not just myself.

**Comment by jeroen** [comment]
OK thank you, we can now build the package again: https://mmaechler.r-universe.dev
